// ── Catálogo de alimentos con equivalencias (NUTRI_CATALOGO_V2) ──
// Extraído de prueba/index.html a este archivo aparte (sep 2026) para no seguir engordando
// el index.html. Cargado vía <script src="alimentos/catalogo.js"> en el <head>, antes del
// script principal de la app — sigue siendo una simple const de nivel superior compartida
// entre <script> del mismo documento, el resto del código no cambia.
const NUTRI_CATALOGO_V2 = {
  arroz_basmati:          { nombre: "Arroz basmati",              categoria: "carbohidrato", peso: "en seco",              kcal: 350, proteina: 7,    carbohidratos: 78,  grasa: 0.5, gramosPorUnidad: null },
  pasta_trigo:            { nombre: "Pasta de trigo",              categoria: "carbohidrato", peso: "en seco",              kcal: 350, proteina: 12,   carbohidratos: 70,  grasa: 1.5, gramosPorUnidad: null },
  avena:                  { nombre: "Avena",                       categoria: "carbohidrato", peso: "en seco",              kcal: 375, proteina: 13,   carbohidratos: 62,  grasa: 7,   gramosPorUnidad: null },
  quinoa:                 { nombre: "Quinoa",                      categoria: "carbohidrato", peso: "en seco",              kcal: 368, proteina: 14,   carbohidratos: 64,  grasa: 6,   gramosPorUnidad: null },
  cuscus:                 { nombre: "Cuscús",                      categoria: "carbohidrato", peso: "en seco",              kcal: 360, proteina: 12,   carbohidratos: 72,  grasa: 1,   gramosPorUnidad: null },
  patata:                 { nombre: "Patata",                      categoria: "carbohidrato", peso: "en crudo",             kcal: 77,  proteina: 2,    carbohidratos: 15.6, grasa: 0.1, gramosPorUnidad: null },
  boniato:                { nombre: "Boniato",                     categoria: "carbohidrato", peso: "en crudo",             kcal: 86,  proteina: 1.6,  carbohidratos: 20,  grasa: 0.1, gramosPorUnidad: null },
  pan_blanco:              { nombre: "Pan blanco",                  categoria: "carbohidrato", peso: "tal como se consume",  kcal: 265, proteina: 9,    carbohidratos: 49,  grasa: 3.2, gramosPorUnidad: null },
  pan_integral:            { nombre: "Pan integral",                categoria: "carbohidrato", peso: "tal como se consume",  kcal: 247, proteina: 13,   carbohidratos: 41,  grasa: 3.4, gramosPorUnidad: null },
  pechuga_pollo:           { nombre: "Pechuga de pollo",            categoria: "proteina",     peso: "en crudo",             kcal: 165, proteina: 31,   carbohidratos: 0,   grasa: 3.6, gramosPorUnidad: null },
  pavo_pechuga:            { nombre: "Pechuga de pavo",             categoria: "proteina",     peso: "en crudo",             kcal: 135, proteina: 30,   carbohidratos: 0,   grasa: 1,   gramosPorUnidad: null },
  ternera_magra:           { nombre: "Ternera magra",               categoria: "proteina",     peso: "en crudo",             kcal: 172, proteina: 21,   carbohidratos: 0,   grasa: 9,   gramosPorUnidad: null },
  lomo_cerdo:              { nombre: "Lomo de cerdo",               categoria: "proteina",     peso: "en crudo",             kcal: 143, proteina: 21,   carbohidratos: 0,   grasa: 6,   gramosPorUnidad: null },
  merluza:                 { nombre: "Merluza",                     categoria: "proteina",     peso: "en crudo",             kcal: 86,  proteina: 17,   carbohidratos: 0,   grasa: 1.5, gramosPorUnidad: null },
  atun_natural:            { nombre: "Atún al natural",             categoria: "proteina",     peso: "escurrido",            kcal: 116, proteina: 26,   carbohidratos: 0,   grasa: 1,   gramosPorUnidad: null },
  sardinas_lata:           { nombre: "Sardinas en lata",            categoria: "proteina",     peso: "escurrido",            kcal: 208, proteina: 25,   carbohidratos: 0,   grasa: 11,  gramosPorUnidad: null },
  claras_huevo:            { nombre: "Claras de huevo",             categoria: "proteina",     peso: "tal como se consume",  kcal: 52,  proteina: 11,   carbohidratos: 0.7, grasa: 0.2, gramosPorUnidad: null },
  yogur_griego_0:          { nombre: "Yogur griego 0%",             categoria: "proteina",     peso: "tal como se consume",  kcal: 59,  proteina: 10,   carbohidratos: 3.6, grasa: 0.4, gramosPorUnidad: null },
  queso_fresco_batido_0:   { nombre: "Queso fresco batido 0%",      categoria: "proteina",     peso: "tal como se consume",  kcal: 45,  proteina: 7.5,  carbohidratos: 3.5, grasa: 0.2, gramosPorUnidad: null },
  aove:                    { nombre: "Aceite de oliva virgen extra",categoria: "grasa",        peso: "tal como se consume",  kcal: 884, proteina: 0,    carbohidratos: 0,   grasa: 100, gramosPorUnidad: null },
  aceitunas:               { nombre: "Aceitunas",                   categoria: "grasa",        peso: "tal como se consume",  kcal: 145, proteina: 1,    carbohidratos: 4,   grasa: 15,  gramosPorUnidad: null },
  salmon:                  { nombre: "Salmón",                      categoria: "mixto",        peso: "en crudo",             kcal: 208, proteina: 20,   carbohidratos: 0,   grasa: 13,  gramosPorUnidad: null },
  huevo_entero:            { nombre: "Huevo entero",                categoria: "mixto",        peso: "tal como se consume",  kcal: 155, proteina: 13,   carbohidratos: 1.1, grasa: 11,  gramosPorUnidad: 60 },
  tofu:                    { nombre: "Tofu",                        categoria: "mixto",        peso: "tal como se consume",  kcal: 76,  proteina: 8,    carbohidratos: 1.9, grasa: 4.8, gramosPorUnidad: null },
  tempeh:                  { nombre: "Tempeh",                      categoria: "mixto",        peso: "tal como se consume",  kcal: 192, proteina: 20,   carbohidratos: 7.6, grasa: 11,  gramosPorUnidad: null },
  almendras:                { nombre: "Almendras",                   categoria: "mixto",        peso: "tal como se consume",  kcal: 579, proteina: 21,   carbohidratos: 22,  grasa: 50,  gramosPorUnidad: null },
  crema_cacahuete:          { nombre: "Crema de cacahuete",          categoria: "mixto",        peso: "tal como se consume",  kcal: 588, proteina: 25,   carbohidratos: 20,  grasa: 50,  gramosPorUnidad: null },
  aguacate:                { nombre: "Aguacate",                    categoria: "mixto",        peso: "tal como se consume",  kcal: 160, proteina: 2,    carbohidratos: 9,   grasa: 15,  gramosPorUnidad: null },

  // ── Fusión con catálogo real NUTRI_FOODS (sep 2026) — solo alimentos añadidos, ──
  // ── ninguna de las 28 claves de arriba se ha tocado ni renombrado ──
  pavo_picado:             { nombre: "Pavo picado",                 categoria: "proteina",     peso: "en crudo",             kcal: 135, proteina: 27,   carbohidratos: 0,   grasa: 3,   gramosPorUnidad: null },
  bacalao:                 { nombre: "Bacalao fresco",               categoria: "proteina",     peso: "en crudo",             kcal: 82,  proteina: 20,   carbohidratos: 0,   grasa: 0.7, gramosPorUnidad: null },
  dorada:                  { nombre: "Dorada",                       categoria: "proteina",     peso: "en crudo",             kcal: 115, proteina: 20,   carbohidratos: 0,   grasa: 4,   gramosPorUnidad: null },
  lubina:                  { nombre: "Lubina",                       categoria: "proteina",     peso: "en crudo",             kcal: 110, proteina: 19,   carbohidratos: 0,   grasa: 3.5, gramosPorUnidad: null },
  gambas:                  { nombre: "Gambas/langostinos",           categoria: "proteina",     peso: "cocido/vapor",         kcal: 99,  proteina: 24,   carbohidratos: 0,   grasa: 1.1, gramosPorUnidad: null },
  mejillones:              { nombre: "Mejillones",                   categoria: "proteina",     peso: "cocido/vapor",         kcal: 86,  proteina: 18,   carbohidratos: 3.7, grasa: 2.2, gramosPorUnidad: null },
  mero:                    { nombre: "Mero",                         categoria: "proteina",     peso: "cocido (papillote)",   kcal: 82,  proteina: 18,   carbohidratos: 0,   grasa: 1,   gramosPorUnidad: null },
  rape:                    { nombre: "Rape",                         categoria: "proteina",     peso: "cocido (papillote)",   kcal: 70,  proteina: 15,   carbohidratos: 0,   grasa: 0.9, gramosPorUnidad: null },
  lenguado:                { nombre: "Lenguado",                     categoria: "proteina",     peso: "en crudo",             kcal: 78,  proteina: 16,   carbohidratos: 0,   grasa: 1.2, gramosPorUnidad: null },
  panga:                   { nombre: "Panga",                        categoria: "proteina",     peso: "cocido (papillote)",   kcal: 90,  proteina: 15,   carbohidratos: 0,   grasa: 3.5, gramosPorUnidad: null },
  emperador:               { nombre: "Emperador/pez espada",         categoria: "proteina",     peso: "en crudo",             kcal: 125, proteina: 20,   carbohidratos: 0,   grasa: 4.5, gramosPorUnidad: null },
  boquerones:              { nombre: "Boquerones en vinagre",        categoria: "proteina",     peso: "tal como se consume",  kcal: 115, proteina: 20,   carbohidratos: 0,   grasa: 3.5, gramosPorUnidad: null },
  calamar:                 { nombre: "Calamar/chipirones",           categoria: "proteina",     peso: "cocido",               kcal: 92,  proteina: 16,   carbohidratos: 3,   grasa: 1.4, gramosPorUnidad: null },
  chirlas:                 { nombre: "Chirlas/almejas",              categoria: "proteina",     peso: "cocido",               kcal: 60,  proteina: 11,   carbohidratos: 2,   grasa: 1,   gramosPorUnidad: null },
  whey:                    { nombre: "Proteína Whey",                categoria: "proteina",     peso: "polvo",                kcal: 375, proteina: 75,   carbohidratos: 7,   grasa: 5,   gramosPorUnidad: null },
  whey_iso:                { nombre: "Proteína Whey Isolada",        categoria: "proteina",     peso: "polvo",                kcal: 370, proteina: 85,   carbohidratos: 2,   grasa: 2,   gramosPorUnidad: null },
  caseina:                 { nombre: "Caseína micelar",              categoria: "proteina",     peso: "polvo",                kcal: 350, proteina: 80,   carbohidratos: 3,   grasa: 2,   gramosPorUnidad: null },
  proteina_vegetal:        { nombre: "Proteína vegetal (guisante)",  categoria: "proteina",     peso: "polvo",                kcal: 363, proteina: 80,   carbohidratos: 4,   grasa: 3,   gramosPorUnidad: null },
  cottage:                 { nombre: "Queso cottage",                categoria: "proteina",     peso: "tal como se consume",  kcal: 98,  proteina: 11,   carbohidratos: 3.4, grasa: 4.3, gramosPorUnidad: null },
  requeson:                { nombre: "Requesón desnatado",           categoria: "proteina",     peso: "tal como se consume",  kcal: 74,  proteina: 11,   carbohidratos: 4,   grasa: 1.5, gramosPorUnidad: null },
  skyr:                    { nombre: "Skyr (yogur islandés)",        categoria: "proteina",     peso: "tal como se consume",  kcal: 63,  proteina: 11,   carbohidratos: 4,   grasa: 0.2, gramosPorUnidad: null },
  jamon_cocido:            { nombre: "Jamón cocido extra",           categoria: "proteina",     peso: "tal como se consume",  kcal: 100, proteina: 18.6, carbohidratos: 0.9, grasa: 2.5, gramosPorUnidad: null },
  jamon_serrano:           { nombre: "Jamón serrano curado",         categoria: "proteina",     peso: "tal como se consume",  kcal: 241, proteina: 31,   carbohidratos: 0,   grasa: 13,  gramosPorUnidad: null },
  paleta_curada:           { nombre: "Paleta curada (ibérica)",      categoria: "proteina",     peso: "tal como se consume",  kcal: 300, proteina: 28,   carbohidratos: 0,   grasa: 20,  gramosPorUnidad: null },
  leche_entera:            { nombre: "Leche entera",                 categoria: "proteina",     peso: "tal como se consume",  kcal: 61,  proteina: 3.1,  carbohidratos: 4.7, grasa: 3.6, gramosPorUnidad: null },
  leche_semi:              { nombre: "Leche semidesnatada",          categoria: "proteina",     peso: "tal como se consume",  kcal: 46,  proteina: 3.2,  carbohidratos: 4.8, grasa: 1.6, gramosPorUnidad: null },
  leche_desnatada:         { nombre: "Leche desnatada",              categoria: "proteina",     peso: "tal como se consume",  kcal: 35,  proteina: 3.4,  carbohidratos: 5.0, grasa: 0.1, gramosPorUnidad: null },
  yogur_natural_desnatado: { nombre: "Yogur natural desnatado",      categoria: "proteina",     peso: "tal como se consume",  kcal: 36,  proteina: 4,    carbohidratos: 5,   grasa: 0.1, gramosPorUnidad: null },
  buey_magro:              { nombre: "Buey magro",                   categoria: "proteina",     peso: "en crudo",             kcal: 148, proteina: 27,   carbohidratos: 0,   grasa: 4.5, gramosPorUnidad: null },
  bacaladilla:             { nombre: "Bacaladilla",                  categoria: "proteina",     peso: "cocido/vapor",         kcal: 74,  proteina: 16,   carbohidratos: 0,   grasa: 1,   gramosPorUnidad: null },
  arroz_integral:          { nombre: "Arroz integral",               categoria: "carbohidrato", peso: "en seco",              kcal: 352, proteina: 7.5,  carbohidratos: 73,  grasa: 2.8, gramosPorUnidad: null },
  pasta_integral:          { nombre: "Pasta integral",               categoria: "carbohidrato", peso: "en seco",              kcal: 340, proteina: 13,   carbohidratos: 66,  grasa: 2.5, gramosPorUnidad: null },
  lentejas:                { nombre: "Lentejas",                     categoria: "carbohidrato", peso: "en seco",              kcal: 353, proteina: 24,   carbohidratos: 60,  grasa: 1.4, gramosPorUnidad: null },
  garbanzos:               { nombre: "Garbanzos",                    categoria: "carbohidrato", peso: "en seco",              kcal: 364, proteina: 19,   carbohidratos: 61,  grasa: 6,   gramosPorUnidad: null },
  alubias_blancas:         { nombre: "Alubias blancas",              categoria: "carbohidrato", peso: "en seco",              kcal: 333, proteina: 23,   carbohidratos: 60,  grasa: 0.8, gramosPorUnidad: null },
  tortitas_arroz:          { nombre: "Tortitas de arroz",            categoria: "carbohidrato", peso: "tal como se consume",  kcal: 384, proteina: 7.5,  carbohidratos: 81,  grasa: 2.4, gramosPorUnidad: null },
  cereales_fitness:        { nombre: "Cereales fitness sin azúcar",  categoria: "carbohidrato", peso: "tal como se consume",  kcal: 320, proteina: 8,    carbohidratos: 65,  grasa: 3,   gramosPorUnidad: null },
  crema_arroz:             { nombre: "Crema de arroz",               categoria: "carbohidrato", peso: "en seco",              kcal: 366, proteina: 8.4,  carbohidratos: 77,  grasa: 2.7, gramosPorUnidad: null },
  corn_flakes:             { nombre: "Corn Flakes",                  categoria: "carbohidrato", peso: "tal como se consume",  kcal: 370, proteina: 6.7,  carbohidratos: 82,  grasa: 1.1, gramosPorUnidad: null },
  pan_campesina:           { nombre: "Pan barra campesina",          categoria: "carbohidrato", peso: "tal como se consume",  kcal: 246, proteina: 7.2,  carbohidratos: 50,  grasa: 1.3, gramosPorUnidad: null },
  tortilla_trigo:          { nombre: "Tortitas de trigo (wrap)",     categoria: "carbohidrato", peso: "tal como se consume",  kcal: 294, proteina: 8.3,  carbohidratos: 50,  grasa: 5.8, gramosPorUnidad: 55 },
  cereales_choco:          { nombre: "Cereales de arroz con chocolate", categoria: "carbohidrato", peso: "tal como se consume", kcal: 380, proteina: 7,   carbohidratos: 81,  grasa: 2,   gramosPorUnidad: null },
  pan_hamburguesa:         { nombre: "Pan de hamburguesa",           categoria: "carbohidrato", peso: "tal como se consume",  kcal: 280, proteina: 9,    carbohidratos: 49,  grasa: 5,   gramosPorUnidad: null },
  maiz_dulce:              { nombre: "Maíz dulce",                   categoria: "carbohidrato", peso: "cocido",               kcal: 96,  proteina: 3.2,  carbohidratos: 19,  grasa: 1.5, gramosPorUnidad: null },
  guisantes:               { nombre: "Guisantes",                    categoria: "carbohidrato", peso: "cocido",               kcal: 81,  proteina: 5.4,  carbohidratos: 14,  grasa: 0.4, gramosPorUnidad: null },
  pan_12cereales:          { nombre: "Pan 12 cereales y semillas",   categoria: "carbohidrato", peso: "tal como se consume",  kcal: 260.5, proteina: 10.7, carbohidratos: 37.2, grasa: 5.8, gramosPorUnidad: null },
  harina_avena:            { nombre: "Harina de avena",              categoria: "carbohidrato", peso: "en seco",              kcal: 364, proteina: 12,   carbohidratos: 60,  grasa: 6.1, gramosPorUnidad: null },
  queso_havarti:           { nombre: "Queso Havarti",                categoria: "grasa",        peso: "tal como se consume",  kcal: 421, proteina: 20,   carbohidratos: 1,   grasa: 37,  gramosPorUnidad: null },
  sardinas_frescas:        { nombre: "Sardinas frescas",             categoria: "mixto",        peso: "en crudo",             kcal: 149, proteina: 25,   carbohidratos: 0,   grasa: 5,   gramosPorUnidad: null },
  caballa:                 { nombre: "Caballa",                      categoria: "mixto",        peso: "en crudo",             kcal: 185, proteina: 19,   carbohidratos: 0,   grasa: 11,  gramosPorUnidad: null },
  atun_aceite:             { nombre: "Atún en aceite de oliva",      categoria: "mixto",        peso: "escurrido",            kcal: 263, proteina: 20,   carbohidratos: 0.7, grasa: 20,  gramosPorUnidad: null },
  carne_picada_ternera:    { nombre: "Carne picada de vacuno",       categoria: "mixto",        peso: "en crudo",             kcal: 226, proteina: 18,   carbohidratos: 2.7, grasa: 16,  gramosPorUnidad: null },
  pollo_asado_piel:        { nombre: "Pollo asado (con piel)",       categoria: "mixto",        peso: "tal como se consume",  kcal: 237, proteina: 27,   carbohidratos: 0,   grasa: 13.5, gramosPorUnidad: null },
  nueces:                  { nombre: "Nueces",                       categoria: "mixto",        peso: "tal como se consume",  kcal: 654, proteina: 15,   carbohidratos: 14,  grasa: 65,  gramosPorUnidad: null },
  cacahuetes:              { nombre: "Cacahuetes tostados",          categoria: "mixto",        peso: "tal como se consume",  kcal: 567, proteina: 26,   carbohidratos: 16,  grasa: 49,  gramosPorUnidad: null },
  anacardos:               { nombre: "Anacardos",                    categoria: "mixto",        peso: "tal como se consume",  kcal: 560, proteina: 20,   carbohidratos: 30,  grasa: 39,  gramosPorUnidad: null },
  queso_fundido_lonchas:   { nombre: "Queso fundido en lonchas",     categoria: "mixto",        peso: "tal como se consume",  kcal: 197.3, proteina: 12.8, carbohidratos: 8, grasa: 12.8, gramosPorUnidad: null },
  avellanas:               { nombre: "Avellanas",                    categoria: "grasa",        peso: "tal como se consume",  kcal: 628, proteina: 15,   carbohidratos: 17,  grasa: 61,  gramosPorUnidad: null },
  aceite_coco:             { nombre: "Aceite de coco virgen",        categoria: "grasa",        peso: "tal como se consume",  kcal: 892, proteina: 0,    carbohidratos: 0,   grasa: 100, gramosPorUnidad: null },
  mantequilla_almendras:   { nombre: "Crema de almendras (100%)",    categoria: "grasa",        peso: "tal como se consume",  kcal: 614, proteina: 21,   carbohidratos: 20,  grasa: 55,  gramosPorUnidad: null },
  semillas_chia:           { nombre: "Semillas de chía",             categoria: "grasa",        peso: "tal como se consume",  kcal: 486, proteina: 17,   carbohidratos: 42,  grasa: 31,  gramosPorUnidad: null },
  semillas_lino:           { nombre: "Semillas de lino",             categoria: "grasa",        peso: "tal como se consume",  kcal: 534, proteina: 18,   carbohidratos: 29,  grasa: 42,  gramosPorUnidad: null },
  // ── Frutas con hidrato relevante (sep 2026) — se meten en carbohidrato porque, a diferencia ──
  // ── de una fruta acuosa (mandarina, sandía...), sí pesan de verdad en el cómputo de macros ──
  platano:                 { nombre: "Plátano",                     categoria: "carbohidrato", peso: "pelado",               kcal: 89,  proteina: 1.1,  carbohidratos: 23,  grasa: 0.3, gramosPorUnidad: 120 },
  uvas:                    { nombre: "Uvas",                        categoria: "carbohidrato", peso: "tal como se consume",  kcal: 69,  proteina: 0.7,  carbohidratos: 18,  grasa: 0.2, gramosPorUnidad: null },
  mango:                   { nombre: "Mango",                       categoria: "carbohidrato", peso: "pelado",               kcal: 60,  proteina: 0.8,  carbohidratos: 15,  grasa: 0.4, gramosPorUnidad: 200 },
  datiles:                 { nombre: "Dátiles",                     categoria: "carbohidrato", peso: "deshuesados",          kcal: 282, proteina: 2.5,  carbohidratos: 75,  grasa: 0.4, gramosPorUnidad: 8 },
  higos:                   { nombre: "Higos",                       categoria: "carbohidrato", peso: "tal como se consume",  kcal: 74,  proteina: 0.8,  carbohidratos: 19,  grasa: 0.3, gramosPorUnidad: 50 },
  pina_natural:            { nombre: "Piña natural",                categoria: "carbohidrato", peso: "pelada",               kcal: 50,  proteina: 0.5,  carbohidratos: 13,  grasa: 0.1, gramosPorUnidad: null },
  pina_lata:               { nombre: "Piña en lata (rodajas)",      categoria: "carbohidrato", peso: "escurrida",            kcal: 55,  proteina: 0.4,  carbohidratos: 13.5, grasa: 0.1, gramosPorUnidad: 30 },

  // ── Alimentos por unidad/lata/tarrina (sep 2026) — valores genéricos de mercado; si Juan usa ──
  // ── siempre la misma marca, ajustar kcal/macros y gramosPorUnidad a la etiqueta real de esa marca ──
  aceitunas_anchoa_lata:   { nombre: "Aceitunas rellenas de anchoa (lata)", categoria: "grasa",  peso: "escurridas",           kcal: 148, proteina: 1.3,  carbohidratos: 3.5, grasa: 15,  gramosPorUnidad: 4 },
  aceitunas_negras_tarrina:{ nombre: "Aceitunas negras (tarrina)",  categoria: "grasa",        peso: "escurridas",           kcal: 130, proteina: 1,    carbohidratos: 5,   grasa: 12,  gramosPorUnidad: 4.5 },
  galletas_maria:          { nombre: "Galletas María",              categoria: "carbohidrato", peso: "tal como se consume",  kcal: 440, proteina: 7.5,  carbohidratos: 75,  grasa: 12,  gramosPorUnidad: 7 },
  queso_cunas:             { nombre: "Queso en cuñas (untable)",    categoria: "grasa",        peso: "tal como se consume",  kcal: 235, proteina: 9,    carbohidratos: 4,   grasa: 19,  gramosPorUnidad: 17.5 },
};
